services:
  caddy:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    links:
      - backend
    environment:
      - BASE_URL
      - API_URL
      - VITE_API_URL=https://${API_URL}
  backend:
    build: backend
    restart: unless-stopped
    environment:
      - SECRET_KEY
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - DOMAIN=${API_URL}
      - OAUTHLIB_INSECURE_TRANSPORT="true"
      - FRONTEND_DOMAIN=${BASE_URL}
      - FRONTEND_URL=https://${BASE_URL}
      - DATABASE_URL=postgres://postgres:postgres@postgres/postgres
  postgres:
    image: postgres:15.1
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data"
volumes:
  caddy_data:
    external: true
  caddy_config:
  db_data:
    external: true